name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npx webpack
    
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.7
      with:
        files: | 
          ncng.js
          LICENSE.md